Update README.md
bytesteams/scaffold-android-lib pull request #4
Opened 2021-04-11 14:37 UTC by okpoint

### Description

[ ] New Feature
[ ] Improve Feature
[ ] Bugfix

_*Please put your description here, it can tell us what change in this PR*_

* add a fantastic feature
* fix a critical defect

### Breaking Change

[ ] Contains breaking change

If your PR contains any breaking change, please list them down here.

* breaking change - 1
* breaking change - 2

### Library update

If your PR contains library update, please provide the comparison link. For example, upgrade Retrofit from v2.8.2 to v2.9.0: https://github.com/square/retrofit/compare/2.8.2...2.9.0

- https://github.com/author/projectName/compare/oldVersion...newVersion

2021-04-11 14:37 UTC, hzwplus approved these changes, later dismissed

2021-04-11 14:55 UTC, lonelyplus approved these changes
testing

2021-04-12 05:13 UTC, hzwplus requested changes
put down a request changes for testing purpose

2021-04-12 05:14 UTC, hzwplus approved these changes

2021-04-12 05:14 UTC, closed without merging